openapi: 3.0.0
info:
  title: Bookinfo APIs
  version: 1.0.0

servers:
  - url: http://details.bookinfo:9080
  - url: http://ratings.bookinfo:9080
  - url: http://reviews.bookinfo:9080

paths:
  /details:
    get:
      summary: Get details
      operationId: getDetails
      responses:
        '200':
          description: Successful response
    # post:
    #   summary: Post details
    #   operationId: postDetails
    #   responses:
    #     '200':
    #       description: Successful response

  /ratings:
    get:
      summary: Get ratings
      operationId: getRatings
      responses:
        '200':
          description: Successful response

  /reviews:
    get:
      summary: Get reviews
      operationId: getReviews
      responses:
        '200':
          description: Successful response
